language: generic
dist: xenial
env: PYTHON_VERSION=3.7.1
python: 3.6

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
 # - pip install --upgrade pip
  - echo "Using flake8 to check Python code"
  - flake8 *.py

install:
  - pip install -r requirements.txt
  - pip show -f flake8
script:
 - echo "On this machine \$LANG=$LANG"
 - echo "Checking our own code passes"
 - flake8 --select BLK *.py
 - cd PytF
 - ./run_tests.sh

branches:
  only:
    - master

notifications:
  email: false
