language: generic
dist: xenial
env: PYTHON_VERSION=3.7.1
python: 3.7

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - pip install coverage
 # - pip install --upgrade pip
 # - echo "Using flake8 to check Python code"
  #- flake8 *.py

install:
  - pip install -r requirements.txt
 # - pip show -f flake8
stages:
  - Static Analysis
  - Test

pylint:
  stage: Static Analysis
  script:
  #- pylint -d C0301 PytF/*.py
script:
  - echo "Script is getting started"
  - cd PytF/
  - pylint -d C0301 PytF/*.py
  - python -m pytest

 #- echo "On this machine \$LANG=$LANG"
 #- echo "Checking our own code passes"
 #- flake8 --select BLK *.py

 #- ./run_tests.sh
after_success:
  - coverage run main.py
  - coverage report

branches:
  only:
    - master

notifications:
  email: false
