language: generic
dist: xenial
env: PYTHON_VERSION=3.7.1
python: 3.7

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - pip install coverage
 # - pip install --upgrade pip
 # - echo "Using flake8 to check Python code"
  #- flake8 *.py

install:
  - pip install -r requirements.txt
 # - pip show -f flake8
script:
  - echo "Script is getting started"
  - cd PytF/
  #- python -m pytest
 # - python -m pylint *.py
#  - python -m flake8 

deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID 
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_DEFAULT_REGION
    bucket: $s3Bucket
    local_dir: PytF
    upload-dir: glue
    skip_cleanup: true
 #- echo "On this machine \$LANG=$LANG"
 #- echo "Checking our own code passes"
 #- flake8 --select BLK *.py

 #- ./run_tests.sh
branches:
  only:
    - master

notifications:
  email: false
