language: generic
dist: xenial
env: PYTHON_VERSION=3.6.2
python: 3.6

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - python -m pip install --upgrade pip
install:
  - pip install --user -r requirements.txt
script:
  - python -m pytest

branches:
  only:
    - master
