language: generic
dist: xenial
env: PYTHON_VERSION=3.7.1
python: 3.7

before_install:
  - sudo apt-get update
  - sudo apt-get install python3 
  - pip install coverage
  - "if grep '\t' *.py *.rst; then echo 'Tabs are bad, please use four spaces.'; false; fi"
  - "if grep -n -r '[[:blank:]]$' *.py *.rst; then echo 'Please remove trailing whitespace.'; false; fi"
  - pip install --upgrade pip setuptools
  - pip install flake8
  - echo "Using flake8 to check Python code"
  - flake8 *.py

  - echo "Using flake8 to check tests (with lots of exclusions)"
  - flake8 --ignore=E501,F401 PytF/*.py
 # - pip install --upgrade pip
  - echo "Using flake8 to check Python code"
   - flake8 *.py

#install:
  - pip install -r requirements.txt
  - pip show -f flake8
script:
  - echo "Script is getting started"
  #- cd PytF/
  - python -m pytest
  - echo "On this machine \$LANG=$LANG"
  #- echo "Checking our own code passes"
  - flake8 --select BLK *.py
  #- cd tests
  #- ./runtes.sh
 # - python -m pylint .
 #- python -m flake8 

before_deploy: "echo 'ready for s3 Deployment?'"

deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID 
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_DEFAULT_REGION
    bucket: $s3Bucket 
    local_dir: PytF
    upload-dir: glue
    skip_cleanup: true
 #- echo "On this machine \$LANG=$LANG"
 #- echo "Checking our own code passes"
 #- flake8 --select BLK *.py
after_deploy: "echo 'Done with s3 files deployment?'"
 #- ./run_tests.sh
branches:
  only:
    - master

notifications:
  email: false