language: generic
dist: xenial
env: PYTHON_VERSION=3.7.1
python: 3.6

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
 # - pip install --upgrade pip
install:
  - pip install -r requirements.txt
script:
  - python -m pytest

branches:
  only:
    - master
